export const POST_USER_LOGIN_SUCCESS = "POST_USER_LOGIN_SUCCESS";
export const POST_USER_LOGOUT_SUCCESS = "POST_USER_LOGOUT_SUCCESS";
export const POST_USER_UPDATE_SUCCESS = "POST_USER_UPDATE_SUCCESS";
